name: ITMusings.com
title: ITMusings.com | A ramble alongside code, design, architecture and software development
description: itmusings 3.0 based on Jekyll Jetflix theme
tags:
  - blog
  - template
  - jekyll

show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Feed
    url: /feed.xml
email: raja@thekollurus.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 
